package HoraDeCodar04.Exercicio03

data class Fruta(
    val portugues: String,
    val ingles: String,
    val espanhol: String,
    val frances: String,
    val indonesio: String,
    val alemao: String,
    val turco: String,
    val italiano: String,
    val swahili: String,
    val tagalog: String
)

val FRUTAS = mutableListOf(
    Fruta(
        "Abacate",
        "Avocado",
        "Aguacate",
        "Avocat",
        "Alpukat",
        "Avocado",
        "Avokado",
        "Avocado",
        "Parachichi",
        "Abukado"
    ),
    Fruta(
        "Abacaxi",
        "Pineapple",
        "Pina",
        "Ananas",
        "Nanas",
        "Ananas",
        "Ananas",
        "Ananas",
        "Nanasi",
        "Pinya"
    ),
    Fruta("Acai", "Acai", "Asai", "Acai", "Acai", "Acai", "Acai", "Acai", "Acai", "Acai"),
    Fruta("Acerola", "Acerola", "Acerola", "Acerola", "Acerola", "Acerola", "Aserola", "Acerola", "Acerola", "Aserola"),
    Fruta("Ameixa", "Plum", "Ciruela", "Prune", "Plum", "Pflaume", "Erik", "Prugna", "Plamu", "Sirwela"),
    Fruta(
        "Amora",
        "Blackberry",
        "Zarzamora",
        "Mure",
        "Blackberry",
        "Brombeere",
        "Bogurtlen",
        "Mora",
        "Blackberry",
        "Lumboy"
    ),
    Fruta("Banana", "Banana", "Platano", "Banane", "Pisang", "Banane", "Muz", "Banana", "Ndizi", "Saging"),
    Fruta("Caja", "Yellow Mombin", "Jobo", "Mombin", "Kedondong", "Mombin", "Mombin", "Mombin", "Mombin", "Mombin"),
    Fruta(
        "Caju",
        "Cashew Apple",
        "Maranon",
        "Pomme Cajou",
        "Jambu Mede",
        "Kaschuapfel",
        "Kaju Elmasi",
        "Anacardo",
        "Korosho",
        "Kasoy"
    ),
    Fruta(
        "Caqui",
        "Persimmon",
        "Caqui",
        "Kaki",
        "Kesemek",
        "Kaki",
        "Trabzon Hurmasi",
        "Cachi",
        "Persimmon",
        "Persimon"
    ),
    Fruta(
        "Carambola",
        "Starfruit",
        "Carambola",
        "Carambole",
        "Belimbing",
        "Sternfrucht",
        "Karambola",
        "Carambola",
        "Carambola",
        "Balimbing"
    ),
    Fruta("Cereja", "Cherry", "Cereza", "Cerise", "Ceri", "Kirsche", "Kiraz", "Ciliegia", "Cheri", "Seresa"),
    Fruta("Ciriguela", "Jocote", "Jocote", "Jocote", "Jocote", "Jocote", "Jocote", "Jocote", "Jocote", "Sineguelas"),
    Fruta(
        "Coco",
        "Coconut",
        "Coco",
        "Noix de Coco",
        "Kelapa",
        "Kokosnuss",
        "Hindistan Cevizi",
        "Cocco",
        "Nazi",
        "Niyog"
    ),
    Fruta("Cupuacu", "Cupuacu", "Copoazu", "Cupuacu", "Cupuacu", "Cupuacu", "Cupuacu", "Cupuacu", "Cupuacu", "Cupuacu"),
    Fruta("Figo", "Fig", "Higo", "Figue", "Ara", "Feige", "Incir", "Fico", "Tini", "Igos"),
    Fruta(
        "Framboesa",
        "Raspberry",
        "Frambuesa",
        "Framboise",
        "Rasberi",
        "Himbeere",
        "Ahududu",
        "Lampone",
        "Rasiberi",
        "Raspberi"
    ),
    Fruta("Goiaba", "Guava", "Guayaba", "Goyave", "Jambu Biji", "Guave", "Guava", "Guava", "Pera", "Bayabas"),
    Fruta(
        "Graviola",
        "Soursop",
        "Guanabana",
        "Corossol",
        "Sirsak",
        "Stachelannone",
        "Tarcin Elmasi",
        "Graviola",
        "Stafeli",
        "Guyabano"
    ),
    Fruta(
        "Jabuticaba",
        "Jaboticaba",
        "Jaboticaba",
        "Jaboticaba",
        "Jaboticaba",
        "Jaboticaba",
        "Jaboticaba",
        "Jaboticaba",
        "Jaboticaba",
        "Jaboticaba"
    ),
    Fruta("Jaca", "Jackfruit", "Jaca", "Jacquier", "Nangka", "Jackfrucht", "Jack Meyvesi", "Giaca", "Fenesi", "Langka"),
    Fruta(
        "Jambo",
        "Rose Apple",
        "Pomarrosa",
        "Jambosier",
        "Jambu Air",
        "Rosenapfel",
        "Gul Elmasi",
        "Melarosa",
        "Tufaha",
        "Makopa"
    ),
    Fruta("Jenipapo", "Genipap", "Huito", "Genipa", "Genipap", "Genipap", "Genipap", "Genipap", "Genipap", "Genipap"),
    Fruta("Kiwi", "Kiwi", "Kiwi", "Kiwi", "Kiwi", "Kiwi", "Kivi", "Kiwi", "Kiwi", "Kiwi"),
    Fruta("Laranja", "Orange", "Naranja", "Orange", "Jeruk", "Orange", "Portakal", "Arancia", "Chungwa", "Kahel"),
    Fruta("Lichia", "Lychee", "Lichi", "Litchi", "Leci", "Litschi", "Lici", "Litchi", "Lichi", "Litsiyas"),
    Fruta("Limao", "Lemon", "Limon", "Citron", "Lemon", "Zitrone", "Limon", "Limone", "Ndimu", "Limon"),
    Fruta("Maca", "Apple", "Manzana", "Pomme", "Apel", "Apfel", "Elma", "Mela", "Tufaha", "Mansanas"),
    Fruta("Mamao", "Papaya", "Papaya", "Papaye", "Pepaya", "Papaya", "Papaya", "Papaya", "Papai", "Papaya"),
    Fruta("Manga", "Mango", "Mango", "Mangue", "Mangga", "Mango", "Mango", "Mango", "Embe", "Mangga"),
    Fruta("Mangaba", "Mangaba", "Mangaba", "Mangaba", "Mangaba", "Mangaba", "Mangaba", "Mangaba", "Mangaba", "Mangaba"),
    Fruta(
        "Maracuja",
        "Passion Fruit",
        "Maracuya",
        "Fruit de la Passion",
        "Markisa",
        "Passionsfrucht",
        "Carkifelek",
        "Frutto della Passione",
        "Pasheni",
        "Pasyon Prutas"
    ),
    Fruta(
        "Melancia",
        "Watermelon",
        "Sandia",
        "Pasteque",
        "Semangka",
        "Wassermelone",
        "Karpuz",
        "Anguria",
        "Tikiti Maji",
        "Pakwan"
    ),
    Fruta("Melao", "Melon", "Melon", "Melon", "Melon", "Melone", "Kavun", "Melone", "Tikiti", "Melon"),
    Fruta(
        "Mirtilo",
        "Blueberry",
        "Arandano",
        "Myrtille",
        "Bluberi",
        "Blaubeere",
        "Yaban Mersini",
        "Mirtillo",
        "Bluberi",
        "Bluberi"
    ),
    Fruta(
        "Morango",
        "Strawberry",
        "Fresa",
        "Fraise",
        "Stroberi",
        "Erdbeere",
        "Cilek",
        "Fragola",
        "Stroberi",
        "Istroberi"
    ),
    Fruta(
        "Nectarina",
        "Nectarine",
        "Nectarina",
        "Nectarine",
        "Nektarin",
        "Nektarine",
        "Nektarin",
        "Nettarina",
        "Nektarini",
        "Nektarina"
    ),
    Fruta("Pera", "Pear", "Pera", "Poire", "Pir", "Birne", "Armut", "Pera", "Pea", "Peras"),
    Fruta("Pessego", "Peach", "Melocoton", "Peche", "Persik", "Pfirsich", "Seftali", "Pesca", "Pichi", "Melokoton"),
    Fruta(
        "Pinha",
        "Sugar Apple",
        "Anon",
        "Attier",
        "Srikaya",
        "Zimtapfel",
        "Seker Elmasi",
        "Cirimoia",
        "Tufaha",
        "Atis"
    ),
    Fruta(
        "Pitanga",
        "Surinam Cherry",
        "Pitanga",
        "Cerise de Cayenne",
        "Pitanga",
        "Surinamkirsche",
        "Pitanga",
        "Pitanga",
        "Pitanga",
        "Pitanga"
    ),
    Fruta(
        "Pitaya",
        "Dragon Fruit",
        "Pitahaya",
        "Fruit du Dragon",
        "Buah Naga",
        "Drachenfrucht",
        "Ejder Meyvesi",
        "Frutto del Drago",
        "Dragon Fruit",
        "Dragon Fruit"
    ),
    Fruta(
        "Roma",
        "Pomegranate",
        "Granada",
        "Grenade",
        "Delima",
        "Granatapfel",
        "Nar",
        "Melograno",
        "Komamanga",
        "Granada"
    ),
    Fruta(
        "Sapoti",
        "Sapodilla",
        "Zapote",
        "Sapotille",
        "Sawo",
        "Sapotille",
        "Sapodilla",
        "Sapodilla",
        "Sapodila",
        "Tsiko"
    ),
    Fruta(
        "Tamarindo",
        "Tamarind",
        "Tamarindo",
        "Tamarin",
        "Asam Jawa",
        "Tamarinde",
        "Demirhindi",
        "Tamarindo",
        "Ukwaju",
        "Sampalok"
    ),
    Fruta(
        "Tangerina",
        "Tangerine",
        "Mandarina",
        "Mandarine",
        "Jeruk Keprok",
        "Mandarine",
        "Mandalina",
        "Mandarino",
        "Chenza",
        "Dalandan"
    ),
    Fruta("Umbu", "Umbu", "Umbu", "Umbu", "Umbu", "Umbu", "Umbu", "Umbu", "Umbu", "Umbu"),
    Fruta("Uva", "Grape", "Uva", "Raisin", "Anggur", "Traube", "Uzum", "Uva", "Zabibu", "Ubas")
)